CREATE CONSTRAINT ON (node:`UNIQUE IMPORT LABEL`) ASSERT (node.`UNIQUE IMPORT ID`) IS UNIQUE;
UNWIND [{_id:6, properties:{filter_prefix:"*", action:"PERMIT", type:"outbound", priority:30}}, {_id:7, properties:{filter_prefix:"*", action:"PERMIT", type:"inbound", priority:100, set_communities:["20:30"]}}, {_id:8, properties:{filter_prefix:"*", action:"PERMIT", type:"inbound", priority:10}}, {_id:9, properties:{filter_prefix:"*", action:"PERMIT", type:"inbound", priority:100}}, {_id:10, properties:{filter_prefix:"*", action:"PERMIT", type:"outbound", priority:20}}, {_id:11, properties:{filter_prefix:"*", action:"PERMIT", type:"outbound", priority:100, filter_as:100}}, {_id:12, properties:{filter_prefix:"*", set_local_pref:300, action:"PERMIT", type:"inbound", priority:400, filter_as:100, set_communities:["20:30"]}}, {_id:13, properties:{filter_prefix:"*", action:"PERMIT", type:"outbound", priority:100, filter_as:100}}, {_id:14, properties:{filter_prefix:"*", action:"PERMIT", type:"inbound", priority:100}}, {_id:15, properties:{filter_prefix:"*", action:"PERMIT", type:"inbound", priority:400}}] AS row
CREATE (n:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row._id}) SET n += row.properties SET n:Filter;
UNWIND [{_id:72, properties:{dPort:53, protocol:"UDP", action:"PERMIT", dIP:"any", sIP:"any", acl:"INPUT", priority:10, sPort:"any", direction:"IN"}}, {_id:73, properties:{dPort:22, protocol:"TCP", action:"PERMIT", dIP:"any", sIP:"any", acl:"INPUT", priority:10, sPort:"any", direction:"IN"}}, {_id:74, properties:{dPort:"any", protocol:"any", action:"DENY", dIP:"any", sIP:"any", acl:"INPUT", priority:100, sPort:"any", direction:"IN"}}, {_id:75, properties:{dPort:"any", protocol:"any", action:"PERMIT", dIP:"any", acl:"OUTPUT", sIP:"any", priority:10, sPort:"any", direction:"OUT"}}, {_id:76, properties:{dPort:"any", protocol:"any", action:"PERMIT", dIP:"any", sIP:"any", acl:"INPUT", priority:10, sPort:"any", direction:"IN"}}, {_id:77, properties:{dPort:"any", protocol:"any", action:"PERMIT", dIP:"any", sIP:"any", acl:"INPUT", priority:10, sPort:"any", direction:"IN"}}, {_id:78, properties:{dPort:"any", protocol:"any", action:"PERMIT", dIP:"any", acl:"OUTPUT", sIP:"any", priority:10, sPort:"any", direction:"IN"}}, {_id:79, properties:{dPort:"any", protocol:"any", action:"PERMIT", dIP:"any", sIP:"any", acl:"INPUT", priority:10, sPort:"any", direction:"IN"}}, {_id:80, properties:{dPort:"any", protocol:"any", action:"PERMIT", dIP:"any", acl:"OUTPUT", sIP:"any", priority:10, sPort:"any", direction:"IN"}}, {_id:81, properties:{dPort:"any", protocol:"any", action:"DENY", dIP:"any", acl:"OUTPUT", sIP:"any", priority:100, sPort:"any", direction:"IN"}}, {_id:117, properties:{dPort:"any", protocol:"any", action:"PERMIT", dIP:"any", sIP:"any", acl:"INPUT", priority:1, sPort:"any", direction:"IN"}}, {_id:118, properties:{dPort:"any", protocol:"any", action:"PERMIT", dIP:"any", sIP:"any", acl:"INPUT", priority:1, sPort:"any", direction:"IN"}}, {_id:119, properties:{dPort:"any", protocol:"any", action:"PERMIT", dIP:"any", sIP:"any", acl:"INPUT", priority:1, sPort:"any", direction:"IN"}}, {_id:120, properties:{dPort:"any", protocol:"any", action:"PERMIT", dIP:"any", sIP:"any", acl:"INPUT", priority:1, sPort:"any", direction:"IN"}}] AS row
CREATE (n:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row._id}) SET n += row.properties SET n:AclRule;
UNWIND [{_id:34, properties:{mac_address:"00:11:22:33:44:55"}}, {_id:35, properties:{mac_address:"00:11:22:33:44:66"}}, {_id:36, properties:{mac_address:"00:11:22:33:44:77"}}, {_id:37, properties:{mac_address:"00:11:22:33:44:88"}}, {_id:38, properties:{mac_address:"00:44:22:33:44:55"}}, {_id:39, properties:{mac_address:"00:44:22:33:44:66"}}, {_id:40, properties:{mac_address:"00:11:22:33:44:55"}}, {_id:41, properties:{mac_address:"00:33:22:33:44:55"}}, {_id:51, properties:{mac_address:"00:11:22:33:44:61"}}, {_id:54, properties:{mac_address:"00:11:22:33:44:62"}}, {_id:58, properties:{mac_address:"11:11:22:33:44:61"}}, {_id:62, properties:{mac_address:"22:11:22:33:44:61"}}, {_id:122, properties:{mac_address:"00:00:00:00:00:00"}}, {_id:125, properties:{mac_address:"00:00:00:00:00:00"}}, {_id:128, properties:{mac_address:"00:00:00:00:00:00"}}, {_id:131, properties:{mac_address:"00:00:00:00:00:00"}}] AS row
CREATE (n:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row._id}) SET n += row.properties SET n:EtherCtp;
UNWIND [{_id:46, properties:{cost:1, simulation:true, to:"192.0.4.0/24", type:"C", via:"192.0.4.1"}}, {_id:47, properties:{cost:1, simulation:true, to:"192.0.5.0/24", type:"C", via:"192.0.5.2"}}, {_id:48, properties:{cost:1, simulation:true, to:"192.0.2.0/24", type:"C", via:"192.0.2.1"}}, {_id:49, properties:{cost:1, simulation:true, to:"192.0.2.0/24", type:"C", via:"192.0.2.2"}}, {_id:64, properties:{to:"0.0.0.0/0", type:"S", via:"2.128.0.1"}}, {_id:65, properties:{to:"0.0.0.0/0", type:"S", via:"2.128.1.1"}}, {_id:66, properties:{cost:1, simulation:true, to:"2.128.0.0/24", type:"C", via:"2.128.0.101"}}, {_id:67, properties:{cost:1, simulation:true, to:"2.128.1.0/24", type:"C", via:"2.128.1.101"}}, {_id:68, properties:{cost:1, simulation:true, to:"192.0.3.0/24", type:"C", via:"192.0.3.1"}}, {_id:69, properties:{cost:1, simulation:true, to:"192.0.3.0/24", type:"C", via:"192.0.3.2"}}, {_id:70, properties:{cost:1, simulation:true, to:"192.0.4.0/24", type:"C", via:"192.0.4.2"}}, {_id:71, properties:{cost:1, simulation:true, to:"192.0.5.0/24", type:"C", via:"192.0.5.1"}}, {_id:106, properties:{cost:2, simulation:true, to:"2.128.1.0/24", type:"B", via:"192.0.2.2"}}, {_id:107, properties:{cost:1, simulation:true, to:"2.128.0.0/24", type:"B", via:"192.0.2.1"}}, {_id:108, properties:{cost:3, simulation:true, to:"2.128.1.0/24", type:"B", via:"192.0.2.1"}}, {_id:109, properties:{cost:3, simulation:true, to:"2.128.0.0/24", type:"B", via:"192.0.3.2"}}, {_id:110, properties:{cost:1, simulation:true, to:"2.128.1.0/24", type:"B", via:"192.0.3.2"}}, {_id:111, properties:{cost:2, simulation:true, to:"2.128.0.0/24", type:"B", via:"192.0.3.1"}}, {_id:112, properties:{cost:1, simulation:true, to:"2.128.0.0/24", type:"B", via:"192.0.4.1"}}, {_id:113, properties:{cost:3, simulation:true, to:"2.128.0.0/24", type:"B", via:"192.0.5.2"}}] AS row
CREATE (n:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row._id}) SET n += row.properties SET n:FibRoute;
UNWIND [{_id:114, properties:{cost:1, simulation:true, to:"2.128.1.0/24", type:"B", via:"192.0.5.2"}}, {_id:115, properties:{cost:2, simulation:true, to:"2.128.1.0/24", type:"B", via:"192.0.4.2"}}, {_id:116, properties:{cost:2, simulation:true, to:"2.128.0.0/24", type:"B", via:"192.0.5.1"}}] AS row
CREATE (n:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row._id}) SET n += row.properties SET n:FibRoute;
UNWIND [{_id:82, properties:{path:[], local_pref:200, origin_as:100, prefix:"2.128.0.0/24", next_hop:"2.128.0.101", simulation:true, best_path:true, med:0, communities:[]}}, {_id:85, properties:{path:[100], local_pref:200, origin_as:100, prefix:"2.128.0.0/24", next_hop:"192.0.4.1", simulation:true, best_path:true, originRouteId:82, med:0, communities:[]}}, {_id:86, properties:{path:[100], local_pref:200, origin_as:100, prefix:"2.128.0.0/24", next_hop:"192.0.2.1", simulation:true, best_path:true, originRouteId:82, med:0, communities:["20:30"]}}, {_id:88, properties:{path:[100, 400], local_pref:200, origin_as:100, prefix:"2.128.0.0/24", next_hop:"192.0.5.1", simulation:true, best_path:false, originRouteId:85, med:0, communities:[]}}, {_id:90, properties:{path:[100, 400, 300], local_pref:200, origin_as:100, prefix:"2.128.0.0/24", next_hop:"192.0.3.2", simulation:true, best_path:false, originRouteId:88, med:0, communities:["20:30"]}}, {_id:92, properties:{path:[100, 200], local_pref:200, origin_as:100, prefix:"2.128.0.0/24", next_hop:"192.0.3.1", simulation:true, best_path:true, originRouteId:86, med:0, communities:["20:30"]}}, {_id:94, properties:{path:[100, 200, 300], local_pref:200, origin_as:100, prefix:"2.128.0.0/24", next_hop:"192.0.5.2", simulation:true, best_path:false, originRouteId:92, med:0, communities:["20:30"]}}, {_id:95, properties:{path:[], local_pref:200, origin_as:300, prefix:"2.128.1.0/24", next_hop:"2.128.1.101", simulation:true, best_path:true, med:0, communities:[]}}, {_id:98, properties:{path:[300], local_pref:200, origin_as:300, prefix:"2.128.1.0/24", next_hop:"192.0.5.2", simulation:true, best_path:true, originRouteId:95, med:0, communities:[]}}, {_id:99, properties:{path:[300], local_pref:200, origin_as:300, prefix:"2.128.1.0/24", next_hop:"192.0.3.2", simulation:true, best_path:true, originRouteId:95, med:0, communities:["20:30"]}}, {_id:101, properties:{path:[300, 400], local_pref:200, origin_as:300, prefix:"2.128.1.0/24", next_hop:"192.0.4.2", simulation:true, best_path:true, originRouteId:98, med:0, communities:[]}}, {_id:103, properties:{path:[300, 400, 100], local_pref:200, origin_as:300, prefix:"2.128.1.0/24", next_hop:"192.0.2.1", simulation:true, best_path:false, originRouteId:101, med:0, communities:["20:30"]}}, {_id:105, properties:{path:[300, 200], local_pref:200, origin_as:300, prefix:"2.128.1.0/24", next_hop:"192.0.2.2", simulation:true, best_path:false, originRouteId:99, med:0, communities:["20:30"]}}] AS row
CREATE (n:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row._id}) SET n += row.properties SET n:Route;
UNWIND [{_id:16, properties:{peer_ip:"192.0.2.2", remote_as:200}}, {_id:17, properties:{peer_ip:"192.0.2.1", remote_as:100}}, {_id:18, properties:{peer_ip:"192.0.3.2", remote_as:300}}, {_id:19, properties:{peer_ip:"192.0.3.1", remote_as:200}}, {_id:20, properties:{peer_ip:"192.0.4.1", remote_as:100}}, {_id:21, properties:{peer_ip:"192.0.5.2", remote_as:300}}, {_id:22, properties:{peer_ip:"192.0.4.2", remote_as:400}}, {_id:23, properties:{peer_ip:"192.0.5.1", remote_as:400}}] AS row
CREATE (n:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row._id}) SET n += row.properties SET n:BgpPeer;
UNWIND [{_id:133, properties:{srcIp:"2.1.1.2", protocol:"UDP", dstPort:33434, dstSubnet:"2.128.1.0/24", simulation:true, srcPort:49152, dstIp:"2.128.1.101"}}] AS row
CREATE (n:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row._id}) SET n += row.properties SET n:Packet;
UNWIND [{_id:0, properties:{subnet_mask:"255.255.255.0", ip_address:"192.0.3.1", subnet_address:"192.0.3.0/24"}}, {_id:1, properties:{subnet_mask:"255.255.255.0", ip_address:"192.0.3.2", subnet_address:"192.0.3.0/24"}}, {_id:2, properties:{subnet_mask:"255.255.255.0", ip_address:"192.0.4.2", subnet_address:"192.0.4.0/24"}}, {_id:3, properties:{subnet_mask:"255.255.255.0", ip_address:"192.0.5.1", subnet_address:"192.0.5.0/24"}}, {_id:4, properties:{subnet_mask:"255.255.255.0", ip_address:"192.0.4.1", subnet_address:"192.0.4.0/24"}}, {_id:5, properties:{subnet_mask:"255.255.255.0", ip_address:"192.0.5.2", subnet_address:"192.0.5.0/24"}}, {_id:24, properties:{subnet_mask:"255.255.255.0", ip_address:"192.0.2.1", subnet_address:"192.0.2.0/24"}}, {_id:25, properties:{subnet_mask:"255.255.255.0", ip_address:"192.0.2.2", subnet_address:"192.0.2.0/24"}}, {_id:52, properties:{subnet_mask:"255.255.255.0", ip_address:"2.128.0.1", subnet_address:"2.128.0.0/24"}}, {_id:55, properties:{subnet_mask:"255.255.255.0", ip_address:"2.128.1.1", subnet_address:"2.128.1.0/24"}}, {_id:59, properties:{subnet_mask:"255.255.255.0", ip_address:"2.128.0.101", subnet_address:"2.128.0.0/24"}}, {_id:63, properties:{subnet_mask:"255.255.255.0", ip_address:"2.128.1.101", subnet_address:"2.128.1.0/24"}}, {_id:123, properties:{subnet_mask:"255.255.255.255", ip_address:"2.1.1.2", subnet_address:"0"}}, {_id:126, properties:{subnet_mask:"255.255.255.255", ip_address:" 2.1.1.1", subnet_address:"0"}}, {_id:129, properties:{subnet_mask:"255.255.255.255", ip_address:"3.3.3.3", subnet_address:"0"}}, {_id:132, properties:{subnet_mask:"255.255.255.255", ip_address:"4.4.4.4", subnet_address:"0"}}] AS row
CREATE (n:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row._id}) SET n += row.properties SET n:Ip4Ctp;
UNWIND [{_id:56, properties:{name:"Host1"}}, {_id:60, properties:{name:"Host2"}}] AS row
CREATE (n:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row._id}) SET n += row.properties SET n:Host;
UNWIND [{_id:42, properties:{name:"Router3", asn:300}}, {_id:43, properties:{name:"Router1", asn:100}}, {_id:44, properties:{name:"Router2", asn:200}}, {_id:45, properties:{name:"Router4", asn:400}}] AS row
CREATE (n:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row._id}) SET n += row.properties SET n:Router;
UNWIND [{_id:26, properties:{port_speed:1000, name:"Ltp1"}}, {_id:27, properties:{port_speed:1000, name:"Ltp2"}}, {_id:28, properties:{port_speed:1000, name:"Ltp3"}}, {_id:29, properties:{port_speed:1000, name:"Ltp4"}}, {_id:30, properties:{port_speed:1000, name:"to_r1"}}, {_id:31, properties:{port_speed:1000, name:"to_r3"}}, {_id:32, properties:{port_speed:1000, name:"to_r4"}}, {_id:33, properties:{port_speed:1000, name:"to_r4"}}, {_id:50, properties:{name:"to_host1"}}, {_id:53, properties:{name:"to_host2"}}, {_id:57, properties:{name:"to_r1"}}, {_id:61, properties:{name:"to_r3"}}, {_id:121, properties:{name:"Loopback0"}}, {_id:124, properties:{name:"Loopback0"}}, {_id:127, properties:{name:"Loopback0"}}, {_id:130, properties:{name:"Loopback0"}}] AS row
CREATE (n:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row._id}) SET n += row.properties SET n:Ltp;
UNWIND [{_id:83, properties:{path:[100], local_pref:200, origin_as:100, prefix:"2.128.0.0/24", next_hop:"192.0.4.1", simulation:true, med:0, communities:[]}}, {_id:84, properties:{path:[100], local_pref:200, origin_as:100, prefix:"2.128.0.0/24", next_hop:"192.0.2.1", simulation:true, med:0, communities:[]}}, {_id:87, properties:{path:[100, 400], local_pref:200, origin_as:100, prefix:"2.128.0.0/24", next_hop:"192.0.5.1", simulation:true, med:0, communities:[]}}, {_id:89, properties:{path:[100, 400, 300], local_pref:200, origin_as:100, prefix:"2.128.0.0/24", simulation:true, next_hop:"192.0.3.2", med:0, communities:[]}}, {_id:91, properties:{path:[100, 200], local_pref:200, origin_as:100, prefix:"2.128.0.0/24", next_hop:"192.0.3.1", simulation:true, med:0, communities:["20:30"]}}, {_id:93, properties:{path:[100, 200, 300], local_pref:200, origin_as:100, prefix:"2.128.0.0/24", simulation:true, next_hop:"192.0.5.2", med:0, communities:["20:30"]}}, {_id:96, properties:{path:[300], local_pref:200, origin_as:300, prefix:"2.128.1.0/24", next_hop:"192.0.5.2", simulation:true, med:0, communities:[]}}, {_id:97, properties:{path:[300], local_pref:200, origin_as:300, prefix:"2.128.1.0/24", next_hop:"192.0.3.2", simulation:true, med:0, communities:[]}}, {_id:100, properties:{path:[300, 400], local_pref:200, origin_as:300, prefix:"2.128.1.0/24", next_hop:"192.0.4.2", simulation:true, med:0, communities:[]}}, {_id:102, properties:{path:[300, 400, 100], local_pref:200, origin_as:300, prefix:"2.128.1.0/24", simulation:true, next_hop:"192.0.2.1", med:0, communities:[]}}, {_id:104, properties:{path:[300, 200], local_pref:200, origin_as:300, prefix:"2.128.1.0/24", next_hop:"192.0.2.2", simulation:true, med:0, communities:["20:30"]}}] AS row
CREATE (n:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row._id}) SET n += row.properties SET n:BgpUpdate;
UNWIND [{start: {_id:56}, end: {_id:64}, properties:{}}, {start: {_id:60}, end: {_id:65}, properties:{}}] AS row
MATCH (start:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.start._id})
MATCH (end:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.end._id})
CREATE (start)-[r:HAS_FIB]->(end) SET r += row.properties;
UNWIND [{start: {_id:133}, end: {_id:106}, properties:{simulation:true}}, {start: {_id:133}, end: {_id:115}, properties:{simulation:true}}] AS row
MATCH (start:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.start._id})
MATCH (end:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.end._id})
CREATE (start)-[r:FWD_WITH]->(end) SET r += row.properties;
UNWIND [{start: {_id:27}, end: {_id:35}, properties:{}}, {start: {_id:26}, end: {_id:34}, properties:{}}, {start: {_id:28}, end: {_id:36}, properties:{}}, {start: {_id:29}, end: {_id:37}, properties:{}}, {start: {_id:30}, end: {_id:38}, properties:{}}, {start: {_id:31}, end: {_id:39}, properties:{}}, {start: {_id:32}, end: {_id:40}, properties:{}}, {start: {_id:33}, end: {_id:41}, properties:{}}, {start: {_id:50}, end: {_id:51}, properties:{}}, {start: {_id:53}, end: {_id:54}, properties:{}}, {start: {_id:57}, end: {_id:58}, properties:{}}, {start: {_id:61}, end: {_id:62}, properties:{}}, {start: {_id:121}, end: {_id:122}, properties:{}}, {start: {_id:124}, end: {_id:125}, properties:{}}, {start: {_id:127}, end: {_id:128}, properties:{}}, {start: {_id:130}, end: {_id:131}, properties:{}}] AS row
MATCH (start:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.start._id})
MATCH (end:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.end._id})
CREATE (start)-[r:HAS_ETHERCTP]->(end) SET r += row.properties;
UNWIND [{start: {_id:45}, end: {_id:46}, properties:{simulation:true}}, {start: {_id:43}, end: {_id:49}, properties:{simulation:true}}, {start: {_id:45}, end: {_id:47}, properties:{simulation:true}}, {start: {_id:43}, end: {_id:66}, properties:{simulation:true}}, {start: {_id:44}, end: {_id:48}, properties:{simulation:true}}, {start: {_id:42}, end: {_id:67}, properties:{simulation:true}}, {start: {_id:42}, end: {_id:68}, properties:{simulation:true}}, {start: {_id:44}, end: {_id:69}, properties:{simulation:true}}, {start: {_id:43}, end: {_id:70}, properties:{simulation:true}}, {start: {_id:42}, end: {_id:71}, properties:{simulation:true}}, {start: {_id:43}, end: {_id:106}, properties:{simulation:true}}, {start: {_id:44}, end: {_id:107}, properties:{simulation:true}}, {start: {_id:44}, end: {_id:108}, properties:{simulation:true}}, {start: {_id:44}, end: {_id:109}, properties:{simulation:true}}, {start: {_id:44}, end: {_id:110}, properties:{simulation:true}}, {start: {_id:42}, end: {_id:111}, properties:{simulation:true}}, {start: {_id:45}, end: {_id:112}, properties:{simulation:true}}, {start: {_id:45}, end: {_id:113}, properties:{simulation:true}}, {start: {_id:45}, end: {_id:114}, properties:{simulation:true}}, {start: {_id:43}, end: {_id:115}, properties:{simulation:true}}] AS row
MATCH (start:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.start._id})
MATCH (end:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.end._id})
CREATE (start)-[r:HAS_FIB]->(end) SET r += row.properties;
UNWIND [{start: {_id:42}, end: {_id:116}, properties:{simulation:true}}] AS row
MATCH (start:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.start._id})
MATCH (end:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.end._id})
CREATE (start)-[r:HAS_FIB]->(end) SET r += row.properties;
UNWIND [{start: {_id:46}, end: {_id:2}, properties:{simulation:true}}, {start: {_id:49}, end: {_id:24}, properties:{simulation:true}}, {start: {_id:47}, end: {_id:3}, properties:{simulation:true}}, {start: {_id:66}, end: {_id:52}, properties:{simulation:true}}, {start: {_id:64}, end: {_id:59}, properties:{}}, {start: {_id:65}, end: {_id:63}, properties:{}}, {start: {_id:48}, end: {_id:25}, properties:{simulation:true}}, {start: {_id:67}, end: {_id:55}, properties:{simulation:true}}, {start: {_id:68}, end: {_id:1}, properties:{simulation:true}}, {start: {_id:69}, end: {_id:0}, properties:{simulation:true}}, {start: {_id:70}, end: {_id:4}, properties:{simulation:true}}, {start: {_id:71}, end: {_id:5}, properties:{simulation:true}}, {start: {_id:106}, end: {_id:24}, properties:{simulation:true}}, {start: {_id:107}, end: {_id:25}, properties:{simulation:true}}, {start: {_id:108}, end: {_id:25}, properties:{simulation:true}}, {start: {_id:109}, end: {_id:0}, properties:{simulation:true}}, {start: {_id:110}, end: {_id:0}, properties:{simulation:true}}, {start: {_id:111}, end: {_id:1}, properties:{simulation:true}}, {start: {_id:112}, end: {_id:2}, properties:{simulation:true}}, {start: {_id:113}, end: {_id:3}, properties:{simulation:true}}] AS row
MATCH (start:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.start._id})
MATCH (end:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.end._id})
CREATE (start)-[r:EGRESS]->(end) SET r += row.properties;
UNWIND [{start: {_id:114}, end: {_id:3}, properties:{simulation:true}}, {start: {_id:115}, end: {_id:4}, properties:{simulation:true}}, {start: {_id:116}, end: {_id:5}, properties:{simulation:true}}] AS row
MATCH (start:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.start._id})
MATCH (end:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.end._id})
CREATE (start)-[r:EGRESS]->(end) SET r += row.properties;
UNWIND [{start: {_id:6}, end: {_id:82}, properties:{simulation:true, action:"PERMIT"}}, {start: {_id:13}, end: {_id:85}, properties:{simulation:true, action:"PERMIT"}}, {start: {_id:11}, end: {_id:88}, properties:{simulation:true, action:"PERMIT"}}, {start: {_id:10}, end: {_id:86}, properties:{simulation:true, action:"PERMIT"}}, {start: {_id:11}, end: {_id:92}, properties:{simulation:true, action:"PERMIT"}}, {start: {_id:11}, end: {_id:95}, properties:{simulation:true, action:"PERMIT"}}, {start: {_id:13}, end: {_id:98}, properties:{simulation:true, action:"PERMIT"}}, {start: {_id:6}, end: {_id:101}, properties:{simulation:true, action:"PERMIT"}}, {start: {_id:10}, end: {_id:99}, properties:{simulation:true, action:"PERMIT"}}] AS row
MATCH (start:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.start._id})
MATCH (end:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.end._id})
CREATE (start)-[r:APPLIES_OUTBOUND_FILTER]->(end) SET r += row.properties;
UNWIND [{start: {_id:43}, end: {_id:26}, properties:{}}, {start: {_id:44}, end: {_id:28}, properties:{}}, {start: {_id:44}, end: {_id:27}, properties:{}}, {start: {_id:42}, end: {_id:29}, properties:{}}, {start: {_id:45}, end: {_id:30}, properties:{}}, {start: {_id:45}, end: {_id:31}, properties:{}}, {start: {_id:43}, end: {_id:32}, properties:{}}, {start: {_id:42}, end: {_id:33}, properties:{}}, {start: {_id:43}, end: {_id:50}, properties:{}}, {start: {_id:42}, end: {_id:53}, properties:{}}, {start: {_id:43}, end: {_id:121}, properties:{}}, {start: {_id:44}, end: {_id:124}, properties:{}}, {start: {_id:42}, end: {_id:127}, properties:{}}, {start: {_id:45}, end: {_id:130}, properties:{}}] AS row
MATCH (start:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.start._id})
MATCH (end:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.end._id})
CREATE (start)-[r:HAS_LTP]->(end) SET r += row.properties;
UNWIND [{start: {_id:43}, end: {_id:6}, properties:{}}, {start: {_id:43}, end: {_id:8}, properties:{}}, {start: {_id:42}, end: {_id:9}, properties:{}}, {start: {_id:44}, end: {_id:10}, properties:{}}, {start: {_id:44}, end: {_id:7}, properties:{}}, {start: {_id:42}, end: {_id:11}, properties:{}}, {start: {_id:45}, end: {_id:12}, properties:{}}, {start: {_id:45}, end: {_id:13}, properties:{}}, {start: {_id:45}, end: {_id:14}, properties:{}}, {start: {_id:44}, end: {_id:15}, properties:{}}] AS row
MATCH (start:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.start._id})
MATCH (end:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.end._id})
CREATE (start)-[r:HAS_FILTER]->(end) SET r += row.properties;
UNWIND [{start: {_id:20}, end: {_id:83}, properties:{simulation:true}}, {start: {_id:17}, end: {_id:84}, properties:{simulation:true}}, {start: {_id:23}, end: {_id:87}, properties:{simulation:true}}, {start: {_id:18}, end: {_id:89}, properties:{simulation:true}}, {start: {_id:19}, end: {_id:91}, properties:{simulation:true}}, {start: {_id:21}, end: {_id:93}, properties:{simulation:true}}, {start: {_id:21}, end: {_id:96}, properties:{simulation:true}}, {start: {_id:18}, end: {_id:97}, properties:{simulation:true}}, {start: {_id:22}, end: {_id:100}, properties:{simulation:true}}, {start: {_id:17}, end: {_id:102}, properties:{simulation:true}}, {start: {_id:16}, end: {_id:104}, properties:{simulation:true}}] AS row
MATCH (start:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.start._id})
MATCH (end:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.end._id})
CREATE (start)-[r:RECEIVES_UPDATE]->(end) SET r += row.properties;
UNWIND [{start: {_id:24}, end: {_id:16}, properties:{}}, {start: {_id:25}, end: {_id:17}, properties:{}}, {start: {_id:0}, end: {_id:18}, properties:{}}, {start: {_id:1}, end: {_id:19}, properties:{}}, {start: {_id:2}, end: {_id:20}, properties:{}}, {start: {_id:3}, end: {_id:21}, properties:{}}, {start: {_id:4}, end: {_id:22}, properties:{}}, {start: {_id:5}, end: {_id:23}, properties:{}}] AS row
MATCH (start:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.start._id})
MATCH (end:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.end._id})
CREATE (start)-[r:HAS_BGP_PEER]->(end) SET r += row.properties;
UNWIND [{start: {_id:121}, end: {_id:117}, properties:{}}, {start: {_id:124}, end: {_id:118}, properties:{}}, {start: {_id:127}, end: {_id:119}, properties:{}}, {start: {_id:130}, end: {_id:120}, properties:{}}] AS row
MATCH (start:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.start._id})
MATCH (end:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.end._id})
CREATE (start)-[r:HAS_ACL]->(end) SET r += row.properties;
UNWIND [{start: {_id:56}, end: {_id:57}, properties:{}}, {start: {_id:60}, end: {_id:61}, properties:{}}] AS row
MATCH (start:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.start._id})
MATCH (end:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.end._id})
CREATE (start)-[r:HAS_LTP]->(end) SET r += row.properties;
UNWIND [{start: {_id:32}, end: {_id:30}, properties:{}}, {start: {_id:33}, end: {_id:31}, properties:{}}, {start: {_id:26}, end: {_id:27}, properties:{}}, {start: {_id:28}, end: {_id:29}, properties:{}}, {start: {_id:50}, end: {_id:57}, properties:{}}, {start: {_id:53}, end: {_id:61}, properties:{}}] AS row
MATCH (start:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.start._id})
MATCH (end:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.end._id})
CREATE (start)-[r:HAS_LINK]->(end) SET r += row.properties;
UNWIND [{start: {_id:85}, end: {_id:83}, properties:{simulation:true}}, {start: {_id:86}, end: {_id:84}, properties:{simulation:true}}, {start: {_id:88}, end: {_id:87}, properties:{simulation:true}}, {start: {_id:90}, end: {_id:89}, properties:{simulation:true}}, {start: {_id:92}, end: {_id:91}, properties:{simulation:true}}, {start: {_id:94}, end: {_id:93}, properties:{simulation:true}}, {start: {_id:98}, end: {_id:96}, properties:{simulation:true}}, {start: {_id:99}, end: {_id:97}, properties:{simulation:true}}, {start: {_id:101}, end: {_id:100}, properties:{simulation:true}}, {start: {_id:103}, end: {_id:102}, properties:{simulation:true}}, {start: {_id:105}, end: {_id:104}, properties:{simulation:true}}] AS row
MATCH (start:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.start._id})
MATCH (end:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.end._id})
CREATE (start)-[r:LEARNED_FROM]->(end) SET r += row.properties;
UNWIND [{start: {_id:14}, end: {_id:83}, properties:{simulation:true, action:"PERMIT"}}, {start: {_id:7}, end: {_id:84}, properties:{simulation:true, action:"PERMIT"}}, {start: {_id:9}, end: {_id:87}, properties:{simulation:true, action:"PERMIT"}}, {start: {_id:7}, end: {_id:89}, properties:{simulation:true, action:"PERMIT"}}, {start: {_id:9}, end: {_id:91}, properties:{simulation:true, action:"PERMIT"}}, {start: {_id:14}, end: {_id:93}, properties:{simulation:true, action:"PERMIT"}}, {start: {_id:14}, end: {_id:96}, properties:{simulation:true, action:"PERMIT"}}, {start: {_id:7}, end: {_id:97}, properties:{simulation:true, action:"PERMIT"}}, {start: {_id:8}, end: {_id:100}, properties:{simulation:true, action:"PERMIT"}}, {start: {_id:7}, end: {_id:102}, properties:{simulation:true, action:"PERMIT"}}, {start: {_id:8}, end: {_id:104}, properties:{simulation:true, action:"PERMIT"}}] AS row
MATCH (start:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.start._id})
MATCH (end:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.end._id})
CREATE (start)-[r:APPLIES_INBOUND_FILTER]->(end) SET r += row.properties;
UNWIND [{start: {_id:133}, end: {_id:121}, properties:{simulation:true}}] AS row
MATCH (start:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.start._id})
MATCH (end:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.end._id})
CREATE (start)-[r:IN_PACKET]->(end) SET r += row.properties;
UNWIND [{start: {_id:43}, end: {_id:76}, properties:{}}, {start: {_id:43}, end: {_id:75}, properties:{}}, {start: {_id:44}, end: {_id:77}, properties:{}}, {start: {_id:44}, end: {_id:78}, properties:{}}, {start: {_id:42}, end: {_id:79}, properties:{}}, {start: {_id:42}, end: {_id:80}, properties:{}}, {start: {_id:45}, end: {_id:81}, properties:{}}] AS row
MATCH (start:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.start._id})
MATCH (end:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.end._id})
CREATE (start)-[r:HAS_ACL]->(end) SET r += row.properties;
UNWIND [{start: {_id:60}, end: {_id:72}, properties:{}}, {start: {_id:60}, end: {_id:73}, properties:{}}, {start: {_id:60}, end: {_id:74}, properties:{}}] AS row
MATCH (start:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.start._id})
MATCH (end:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.end._id})
CREATE (start)-[r:HAS_ACL]->(end) SET r += row.properties;
UNWIND [{start: {_id:34}, end: {_id:24}, properties:{}}, {start: {_id:35}, end: {_id:25}, properties:{}}, {start: {_id:36}, end: {_id:0}, properties:{}}, {start: {_id:37}, end: {_id:1}, properties:{}}, {start: {_id:38}, end: {_id:2}, properties:{}}, {start: {_id:39}, end: {_id:3}, properties:{}}, {start: {_id:40}, end: {_id:4}, properties:{}}, {start: {_id:41}, end: {_id:5}, properties:{}}, {start: {_id:51}, end: {_id:52}, properties:{}}, {start: {_id:54}, end: {_id:55}, properties:{}}, {start: {_id:58}, end: {_id:59}, properties:{}}, {start: {_id:62}, end: {_id:63}, properties:{}}, {start: {_id:122}, end: {_id:123}, properties:{}}, {start: {_id:125}, end: {_id:126}, properties:{}}, {start: {_id:128}, end: {_id:129}, properties:{}}, {start: {_id:131}, end: {_id:132}, properties:{}}] AS row
MATCH (start:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.start._id})
MATCH (end:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.end._id})
CREATE (start)-[r:HAS_IP4CTP]->(end) SET r += row.properties;
UNWIND [{start: {_id:117}, end: {_id:133}, properties:{simulation:true, action:"PERMIT"}}] AS row
MATCH (start:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.start._id})
MATCH (end:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.end._id})
CREATE (start)-[r:APPLIES_IN_ACL]->(end) SET r += row.properties;
UNWIND [{start: {_id:22}, end: {_id:83}, properties:{simulation:true}}, {start: {_id:16}, end: {_id:84}, properties:{simulation:true}}, {start: {_id:21}, end: {_id:87}, properties:{simulation:true}}, {start: {_id:19}, end: {_id:89}, properties:{simulation:true}}, {start: {_id:18}, end: {_id:91}, properties:{simulation:true}}, {start: {_id:23}, end: {_id:93}, properties:{simulation:true}}, {start: {_id:23}, end: {_id:96}, properties:{simulation:true}}, {start: {_id:19}, end: {_id:97}, properties:{simulation:true}}, {start: {_id:20}, end: {_id:100}, properties:{simulation:true}}, {start: {_id:16}, end: {_id:102}, properties:{simulation:true}}, {start: {_id:17}, end: {_id:104}, properties:{simulation:true}}] AS row
MATCH (start:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.start._id})
MATCH (end:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.end._id})
CREATE (start)-[r:BGP_UPDATE_TO_SEND]->(end) SET r += row.properties;
UNWIND [{start: {_id:43}, end: {_id:82}, properties:{simulation:true}}, {start: {_id:45}, end: {_id:85}, properties:{simulation:true}}, {start: {_id:44}, end: {_id:86}, properties:{simulation:true}}, {start: {_id:42}, end: {_id:88}, properties:{simulation:true}}, {start: {_id:44}, end: {_id:90}, properties:{simulation:true}}, {start: {_id:42}, end: {_id:92}, properties:{simulation:true}}, {start: {_id:45}, end: {_id:94}, properties:{simulation:true}}, {start: {_id:42}, end: {_id:95}, properties:{simulation:true}}, {start: {_id:45}, end: {_id:98}, properties:{simulation:true}}, {start: {_id:44}, end: {_id:99}, properties:{simulation:true}}, {start: {_id:43}, end: {_id:101}, properties:{simulation:true}}, {start: {_id:44}, end: {_id:103}, properties:{simulation:true}}, {start: {_id:43}, end: {_id:105}, properties:{simulation:true}}] AS row
MATCH (start:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.start._id})
MATCH (end:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.end._id})
CREATE (start)-[r:HAS_ROUTE]->(end) SET r += row.properties;
UNWIND [{start: {_id:16}, end: {_id:17}, properties:{}}, {start: {_id:18}, end: {_id:19}, properties:{}}, {start: {_id:22}, end: {_id:20}, properties:{}}, {start: {_id:23}, end: {_id:21}, properties:{}}] AS row
MATCH (start:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.start._id})
MATCH (end:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.end._id})
CREATE (start)-[r:PEERS_WITH]->(end) SET r += row.properties;
UNWIND [{start: {_id:75}, end: {_id:133}, properties:{simulation:true, action:"PERMIT"}}] AS row
MATCH (start:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.start._id})
MATCH (end:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.end._id})
CREATE (start)-[r:APPLIES_OUT_ACL]->(end) SET r += row.properties;
MATCH (n:`UNIQUE IMPORT LABEL`)  WITH n LIMIT 20000 REMOVE n:`UNIQUE IMPORT LABEL` REMOVE n.`UNIQUE IMPORT ID`;
DROP CONSTRAINT ON (node:`UNIQUE IMPORT LABEL`) ASSERT (node.`UNIQUE IMPORT ID`) IS UNIQUE;
